language: scala
scala:
- 2.10.3
deploy:
  provider: heroku
  api_key:
    secure: lJkGZWAHUTXF+Mi5sE+upm7hHY5VddU//fSxItV//tlpc+CRb8gJltxH7Dx+5qoi0TQhY9zLmFwYdPu7KBvz0dsvcqZtSOTBdrVvBQStYFyjlD2fuIPUnvl4SA+HhHLkApgF/205EdOHkEM0XA93J+1W6uluBmL0E3BF14QYWk8=
  app: hall-hooks
  on:
    repo: drdamour/hall-hooks
