language: scala
script: sbt coveralls
scala:
- 2.10.3
deploy:
  provider: heroku
  api_key:
    secure: hUxppngfpBsAl0jafG0GF4Z6O92spf0GraQ7rcQAi2RWWNUnl9FJaMvtGaMLfZcXq56r6OzCHLHFJQRnDU/uY5ZzZ2rVUG1o65jLuh5zZ3rHX8kvOsIQsZneVNsdRiO/1dXKBLuoC68VJUC6qS4anXNMu6mO2Bu4qGtoCm4Z+LE=
  app: hall-hooks
  on:
    repo: drdamour/hall-hooks
notifications:
  webhooks:
    urls:
    - secure: YRh/rH/5VpzdYn1hzPuQblPsEHwWbhr2kS25rt6iWj1txNTSRCVV8N3L0xsb1TEQTTKjut2nukjfc79xaBqFuoQG/hAs/CIYk+WK7pcojq5y266MaJvr/PxBVEmrK8SQOchCxAWKVX1UfY/Dhix28RJUipky5Cby/fsasO1Ik5o=
    on_start: true
env:
  matrix:
    secure: D+/J3OF5ZxcrDSU5rvbvKeCMkxskgPD8culXpQJhSWbqyzJtufl5rBSGdsASGne8e/bnSDdihD29Qb9/IaxHR39vY5humgu0YncDfG/x33A3UVlCLQvLobVEvzkofhvDDJZQlBzZXnnWw+Xnhfdp/wrkLPrh+mLEA3AprvkWDaw=
