language: scala
script: sbt coveralls
scala:
- 2.10.3
deploy:
  provider: heroku
  api_key:
    secure: hUxppngfpBsAl0jafG0GF4Z6O92spf0GraQ7rcQAi2RWWNUnl9FJaMvtGaMLfZcXq56r6OzCHLHFJQRnDU/uY5ZzZ2rVUG1o65jLuh5zZ3rHX8kvOsIQsZneVNsdRiO/1dXKBLuoC68VJUC6qS4anXNMu6mO2Bu4qGtoCm4Z+LE=
  app: hall-hooks
  on:
    repo: drdamour/hall-hooks
notifications:
  webhooks:
    urls:
    - secure: iq80ADDx4b61yzEz4wx80p5CTF441K1ZZK4XssTr/7Nm+QG0mEG3Ri18qBTbqaix9ATV4boiv+oAlr7yh3cBEixnm2VH7zjCjbFeYtLFZNJRI7Dwj7Xyi1LOEa7D4EX90jHa/keaTqmlzm/WCXWZDsCDs0M7n9+Z+KzMWnF0MbE=
    on_start: true
env:
  matrix:
    secure: D+/J3OF5ZxcrDSU5rvbvKeCMkxskgPD8culXpQJhSWbqyzJtufl5rBSGdsASGne8e/bnSDdihD29Qb9/IaxHR39vY5humgu0YncDfG/x33A3UVlCLQvLobVEvzkofhvDDJZQlBzZXnnWw+Xnhfdp/wrkLPrh+mLEA3AprvkWDaw=
